name: Docker Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'external-api/**'
      - 'public-api/**'
      - 'packages/**'
      - 'package.json'
      - 'nx.json'
      - 'tsconfig.base.json'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app:
          - name: external-api
            dockerfile: external-api/Dockerfile
            image: yourdockerhubusername/external-api   ## Need to update user name "yourdockerhubusername"
          - name: public-api
            dockerfile: public-api/Dockerfile
            image: yourdockerhubusername/public-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  ## User name require to update and password also
          password: ${{ secrets.DOCKER_PASSWORD }}  ## Password

      - name: Build and Push Docker image - ${{ matrix.app.name }}
        run: |
          docker build -t ${{ matrix.app.image }}:latest -f ${{ matrix.app.dockerfile }} .
          docker push ${{ matrix.app.image }}:latest
